<script setup>
</script>

<template>
    <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="@/assets/map.jpeg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="Definition door" title="Definition door" href="/definition-door" coords="978,353,732,181" shape="rect">
    <area target="" alt="Biomedical research alley" title="Biomedical research alley" href="/research/biomedical" coords="630,976,271,770" shape="rect">
    <area target="" alt="Funding" title="Funding" href="/funding" coords="708,740,483,552" shape="rect">
    <area target="" alt="Team Assembly" title="Team Assembly" href="/team/assembly" coords="1213,845,1009,626" shape="rect">
    <area target="" alt="Medical research" title="Medical research" href="/research/medical" coords="1642,494,1931,626" shape="rect">
</map>
</template>